name: latihan_signalr_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  get: 4.6.1
  http: 0.13.4
  intl: 0.17.0
  signalr_core: 1.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

